### PR TITLE
adding extension to license reference

### PR DESCRIPTION
**Pull request by mkodell**

### CODE REVIEW

**Review by iBotPeaches — APPROVED** [review]

**Comment by erik-perri** [comment]
Do you mind fixing the Overriding Headers link while you're fixing this?  It is missing an `r`.

**Comment by mkodell** [comment]
> Do you mind fixing the Overriding Headers link while you're fixing this? It is missing an `r`.

Sure.

**Review by erik-perri — APPROVED** [review]

**Review by iBotPeaches — APPROVED** [review]

**Comment by mkodell** [comment]
I believe that adding the full links to the categories will allow us to link directly to them from the open source website.

**Review by nicomaurer — APPROVED** [review]

**Comment by mkodell** [comment]
Okay, I think that was the last thing I needed to change.

**Review by erik-perri — APPROVED** [review]

**Review by brianangulo — APPROVED** [review]

**Pull request merged**
